version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.12
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run: 
        name: Install NPM Dependencies
        command: npm install
  deploy-job:
    docker:
      - image: my-image-version-tag
    working_directory: /tmp/my-project
    steps:
      - run:
        name: Deploy Master to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_HOSTING_TOKEN

workflows:
  version: 2
  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master